package com.episodera.core.network

import com.episodera.core.model.*
import javax.inject.Inject

class EpisodEraRepository @Inject constructor(private val api: EpisodEraApi) {
    suspend fun health() = api.health()
    suspend fun trending(pagination: PaginationParams = PaginationParams()) = api.trending(pagination.page, pagination.pageSize)
    suspend fun trendingMovies(pagination: PaginationParams = PaginationParams()) = api.trendingMovies(pagination.page, pagination.pageSize)
    suspend fun trendingTv(pagination: PaginationParams = PaginationParams()) = api.trendingTv(pagination.page, pagination.pageSize)
    suspend fun search(query: String, pagination: PaginationParams = PaginationParams()) = api.search(query, pagination.page, pagination.pageSize)
    suspend fun detail(type: MediaType, id: Int) = api.detail(type.wireValue, id)
    suspend fun tvSeason(id: Int, season: Int) = api.tvSeason(id, season)
    suspend fun discussions(type: MediaType, id: Int) = api.discussions(type.wireValue, id)
    suspend fun createDiscussion(type: MediaType, id: Int, body: String, seasonNumber: Int? = null, episodeNumber: Int? = null) =
        api.createDiscussion(type.wireValue, id, CreateDiscussionInput(body, seasonNumber, episodeNumber))
    suspend fun franchises() = api.franchises()
    suspend fun franchise(slug: String) = api.franchise(slug)
    suspend fun discoverySuggestions(mood: String? = null, maxMinutes: Int? = null, providers: String? = null, region: String? = null) =
        api.discoverySuggestions(mood, maxMinutes, providers, region)
    suspend fun discoveryList(id: String, page: Int? = null, maxMinutes: Int? = null, providers: String? = null, region: String? = null) =
        api.discoveryList(id, page, maxMinutes, providers, region)
    suspend fun watchlist(pagination: PaginationParams = PaginationParams()) = api.watchlist(pagination.pageSize, pagination.pageToken)
    suspend fun addWatchlist(input: AddWatchlistItemInput) = api.addWatchlist(input)
    suspend fun updateWatchlist(itemId: String, status: WatchlistStatus) = api.updateWatchlist(itemId, UpdateWatchlistStatusBody(status))
    suspend fun removeWatchlist(itemId: String) = api.removeWatchlist(itemId)
    suspend fun likes(pagination: PaginationParams = PaginationParams()) = api.likes(pagination.pageSize, pagination.pageToken)
    suspend fun addLike(input: AddLikedItemInput) = api.addLike(input)
    suspend fun removeLike(itemId: String) = api.removeLike(itemId)
    suspend fun progress(pagination: PaginationParams = PaginationParams()) = api.progress(pagination.pageSize, pagination.pageToken)
    suspend fun getProgress(showId: Int) = api.getProgress(showId)
    suspend fun markEpisode(showId: Int, input: MarkEpisodeWatchedInput) = api.markEpisode(showId, input)
    suspend fun batchEpisodes(showId: Int, input: BatchEpisodeProgressInput) = api.batchEpisodes(showId, input)
    suspend fun unmarkEpisode(showId: Int, episodeKey: String) = api.unmarkEpisode(showId, episodeKey)
    suspend fun profile() = api.profile()
    suspend fun updateProfile(input: UpdateUserProfileInput) = api.updateProfile(input)
    suspend fun settings() = api.settings()
    suspend fun updateSettings(settings: UserSettings) = api.updateSettings(settings)
    suspend fun stats() = api.stats()
    suspend fun recap(year: Int? = null) = api.recap(year)
    suspend fun history(pagination: PaginationParams = PaginationParams()) = api.history(pagination.pageSize, pagination.pageToken)
    suspend fun updateHistory(id: String, input: UpdateHistoryInput) = api.updateHistory(id, input)
    suspend fun deleteHistory(id: String) = api.deleteHistory(id)
    suspend fun achievements() = api.achievements()
    suspend fun friends() = api.friends()
    suspend fun requestFriend(friendCode: String) = api.requestFriend(mapOf("friendCode" to friendCode))
    suspend fun updateFriend(userId: String, status: String) = api.updateFriend(userId, mapOf("status" to status))
    suspend fun feed() = api.feed()
    suspend fun compatibility(userId: String) = api.compatibility(userId)
    suspend fun challenges(friendUserId: String? = null) = api.challenges(friendUserId)
    suspend fun franchiseProgress(slug: String, order: FranchiseOrder = FranchiseOrder.RELEASE) = api.franchiseProgress(slug, order)
    suspend fun puzzleToday() = api.dailyPuzzle()
    suspend fun guessPuzzle(id: String, request: GuessRequest) = api.guessPuzzle(id, request)
    suspend fun puzzleStats() = api.puzzleStats()
    suspend fun export() = api.export()
    suspend fun deleteAccount() = api.deleteAccount()
    suspend fun resolveTvTime(shows: List<ResolveTvTimeShowInput>) = api.resolveTvTime(mapOf("shows" to shows))
    suspend fun upsertMapping(mapping: MediaMapping) = api.upsertMapping(mapping)
    suspend fun createImport(provider: String = "tv_time", sourceHash: String? = null) = api.createImport(mapOf("provider" to provider, "sourceHash" to sourceHash))
    suspend fun getImport(id: String) = api.getImport(id)
    suspend fun stageWatchlist(id: String, items: List<ImportWatchlistItemInput>) = api.stageWatchlist(id, mapOf("items" to items))
    suspend fun stageEpisodes(id: String, items: List<ImportEpisodeInput>) = api.stageEpisodes(id, mapOf("episodes" to items))
    suspend fun commitImport(id: String) = api.commitImport(id)
    suspend fun runImport(id: String, maxEpisodeWrites: Int = 100) = api.runImport(id, mapOf("maxEpisodeWrites" to maxEpisodeWrites))
}
